### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by garenchan** [pallets/pallets-sphinx-themes#9]
```
Traceback (most recent call last):
  File "/home/travis/build/garenchan/werkzeug/.tox/docs-html/lib/python3.6/site-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/home/travis/build/garenchan/werkzeug/.tox/docs-html/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 2, in <module>
    from pallets_sphinx_themes import ProjectLink, get_version
  File "/home/travis/build/garenchan/werkzeug/.tox/docs-html/lib/python3.6/site-packages/pallets_sphinx_themes/__init__.py", line 15, in <module>
    from .versions import load_versions
  File "/home/travis/build/garenchan/werkzeug/.tox/docs-html/lib/python3.6/site-packages/pallets_sphinx_themes/versions.py", line 7, in <module>
    from packaging import version as pv
ModuleNotFoundError: No module named 'packaging'
```
``pallets-sphinx-themes`` uses ``packaging`` library. But ``packaging`` may not be installed.

I know newest ``sphinx`` depends on ``packaging`` but versions older than ``1.7.0`` not.

**Comment by davidism** [comment]
Released 1.1.1
